name: Build OpenWrt for Cudy TR3000

on:
  workflow_dispatch:
    inputs:
      openwrt_ver:
        description: 'OpenWrt branch/tag (23.05-SNAPSHOT, main, 24.10.0 等)'
        required: true
        default: 23.05-SNAPSHOT
      custom_config:
        description: '自定义 .config 完整链接（留空则使用内置最优配置）'
        required: false
        type: string
      ssh_actions:
        description: '编译完开启 SSH 调试（调试用）'
        required: false
        type: boolean
        default: false

env:
  TARGET: mediatek/filogic
  SUBTARGET: mt7981
  DEVICE: cudy_tr3000-v1
  
  # 强制加入 kmod-mtd-rw（允许对 NAND/UBI 进行写操作，解锁根分区写权限必备）
  PACKAGES: >-
    luci luci-ssl-openssl luci-app-opkg luci-app-sqm
    luci-app-wol luci-app-uugameaccel luci-app-ddns ddns-scripts-cloudflare
    luci-app-turboacc kmod-mt7981-firmware wpad-openssl
    kmod-mtd-rw kmod-mtd-rw_insmod   # <── 关键两行，强制包含
    -wpad-basic-mbedtls -wpad-mini -wpad-basic-wolfssl

  FILES: "files"
  KEEP_DAYS: 7

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo docker image prune -af || true
        df -h

    - name: Install build dependencies
      run: |
        sudo apt update -y
        sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            zlib1g-dev lzop python3 python3-pip rsync unzip wget time \
            qemu-utils u-boot-tools

    - name: Clone OpenWrt source
      run: |
        git clone --depth 1 https://git.openwrt.org/openwrt/openwrt.git openwrt
        cd openwrt
        if [[ "${{ inputs.openwrt_ver }}" != "main" && "${{ inputs.openwrt_ver }}" != "master" ]]; then
          git fetch --depth=1 origin ${{ inputs.openwrt_ver }}
          git checkout ${{ inputs.openwrt_ver }}
        fi

    - name: Update & install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Generate or download config
      run: |
        cd openwrt
        if [[ -n "${{ inputs.custom_config }}" ]]; then
          echo "使用用户提供的自定义配置"
          wget -q ${{ inputs.custom_config }} -O .config
        else
          cat > .config <<EOF
        CONFIG_TARGET_${{ env.TARGET }}=y
        CONFIG_TARGET_${{ env.TARGET }}_${{ env.SUBTARGET }}=y
        CONFIG_TARGET_${{ env.TARGET }}_${{ env.SUBTARGET }}_DEVICE_${{ env.DEVICE }}=y

        # 强制启用 mtd-rw（去只读锁必备）
        CONFIG_PACKAGE_kmod-mtd-rw=y
        CONFIG_PACKAGE_kmod-mtd-rw_insmod=y   # 部分内核需要这个子包

        # LuCI 与常用软件包
        CONFIG_PACKAGE_luci=y
        CONFIG_LUCI_SRCDIET=y
        ${{ env.PACKAGES }}

        # 性能相关
        CONFIG_PACKAGE_kmod-tcp-bbr=y
        CONFIG_PACKAGE_luci-app-turboacc=y
        CONFIG_TURBOACC_ENABLE_SHORTCUT_FE=y
        CONFIG_TURBOACC_ENABLE_FULLCONENAT=y

        # 其他常用
        CONFIG_PACKAGE_luci-app-ttyd=y
        CONFIG_PACKAGE_luci-app-adguardhome=y
        CONFIG_PACKAGE_luci-app-passwall=y
        CONFIG_PACKAGE_luci-app-openclash=y

        # 版本信息
        CONFIG_GR64=y
        CONFIG_IMAGEOPT=y
        CONFIG_VERSIONOPT=y
        CONFIG_VERSION_DIST="OpenWrt"
        CONFIG_VERSION_NUMBER="$(date +%Y%m%d)"
        EOF
        fi

        make defconfig

    - name: Copy custom files (if exist)
      if: env.FILES != ''
      run: |
        if [ -d "${{ github.workspace }}/${{ env.FILES }}" ]; then
          mkdir -p openwrt/files
          cp -r ${{ github.workspace }}/${{ env.FILES }}/* openwrt/files/
        fi

    - name: Cache dl directory
      uses: actions/cache@v4
      with:
        path: openwrt/dl
        key: dl-${{ hashFiles('openwrt/.config') }}-${{ inputs.openwrt_ver }}
        restore-keys: dl-${{ inputs.openwrt_ver }}-

    - name: Build firmware
      run: |
        cd openwrt
        make -j$(nproc) V=s || make -j1 V=s

    - name: Organize artifacts
      run: |
        mkdir -p artifacts
        find openwrt/bin -type f \( -name "*.bin" -o -name "*.img" -o -name "*.squashfs*" \) -exec cp {} artifacts/ \;
        cd artifacts
        sha256sum * > sha256sums
        ls -lh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-TR3000-${{ inputs.openwrt_ver }}-${{ github.sha }}
        path: artifacts/*
        retention-days: ${{ env.KEEP_DAYS }}

    - name: Enable SSH debug (optional)
      if: inputs.ssh_actions == true
      uses: luchihoratiu/debug-via-ssh@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DEBUG_SCRIPT: |
          cd ~/openwrt && bash
